# Generated by Django 4.2.30 on 2026-05-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_messaging_and_case_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_case_notes',
            field=models.TextField(blank=True, default='', help_text='Notas del tutor sobre la mascota o el caso.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='messaging_enabled',
            field=models.BooleanField(default=False, help_text='El veterinario habilita el chat con el tutor para esta cita.'),
        ),
    ]
