# Generated by Django 4.2.30 on 2026-05-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_client_case_notes_and_more'),
        ('appointments', '0009_appointment_pet_name'),
    ]

    operations = [
    ]
