from .available_slots import AvailableSlotsView
from .create_appointment import (
    AppointmentAcceptView,
    AppointmentCancelView,
    AppointmentClinicalRecordView,
    AppointmentCompleteView,
    AppointmentCreateView,
    AppointmentDetailView,
    AppointmentFinalizeTeleconsultationView,
    AppointmentListCreateView,
    AppointmentRejectView,
    AppointmentRescheduleView,
    AppointmentStartTeleconsultationView,
    ClientAppointmentListView,
    ExpiredPendingCancellationView,
    MedicalFileListCreateView,
    MessageListCreateView,
    SurgeryApprovalView,
    SurgeryRoomListView,
    TeleconsultationByUuidView,
    VeterinarianAppointmentListView,
)
